name: Screenshot website
on: push

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master # Required for headful puppeteer
      env:
        CI: 'true'
        
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@v2.1.0
      with:
        url: https://krasch.io/trans-europe-planner/
        fullPage: 'false'
        noCommitHashFileName: 'true'

    - name: Set current datetime as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV

    - name: Rename file to include current datetime
      run: cp screenshots/desktopPage1920x1080.jpeg screenshots/${{ env.NOW }}_desktop1920x1080.jpeg
        
    - uses: actions/upload-artifact@v2 # Uplaod screenshots to Actions Artifacts via actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-screenshots
